CREATE OR REPLACE FUNCTION printf(format text, VARIADIC "any")
RETURNS text
AS 'MODULE_PATHNAME', '_printf_core'
LANGUAGE C IMMUTABLE STRICT;

CREATE OR REPLACE FUNCTION printf2(format text, VARIADIC "any")
RETURNS text
AS 'MODULE_PATHNAME', '_printf_core2'
LANGUAGE C IMMUTABLE STRICT;
